#!/usr/bin/env node
'use strict';
const {spawn}=require('child_process');
const fs=require('fs');
const os=require('os');
const path=require('path');
const net=require('net');
const pkg=require('../package.json');

function freePort(){return new Promise((resolve,reject)=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});s.on('error',reject);});}
function cookieFrom(res){const raw=res.headers.get('set-cookie')||'';return raw.split(';')[0];}
async function waitFor(url,tries=60){for(let i=0;i<tries;i++){try{const r=await fetch(url);if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,100));}throw new Error(`Server did not become ready: ${url}`);}
async function json(base,pathname,{method='GET',body,cookie,headers={}}={}){
  const h={...headers}; if(body!==undefined){h['content-type']='application/json';body=JSON.stringify(body);} if(cookie)h.cookie=cookie;
  const res=await fetch(base+pathname,{method,body,headers:h,redirect:'manual'});
  const text=await res.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={text}};
  return {res,data};
}
const checks=[];function check(name,ok,detail=''){checks.push([name,Boolean(ok),detail]);}
(async()=>{
  const port=await freePort();const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'workshop-v9-int-'));const root=path.resolve(__dirname,'..');
  const child=spawn(process.execPath,['server.js'],{cwd:root,env:{...process.env,HOST:'127.0.0.1',PORT:String(port),WORKSHOP_DATA_DIR:dataDir,WORKSHOP_DEV_AUTH:'1',WORKSHOP_SEED_DEMO:'1',NODE_ENV:'development'},stdio:['ignore','pipe','pipe']});
  let logs='';child.stdout.on('data',d=>logs+=d);child.stderr.on('data',d=>logs+=d);
  const base=`http://127.0.0.1:${port}`;
  try{
    await waitFor(base+'/api/meta');
    let r=await json(base,'/api/meta');check(`meta reports v${pkg.version}`,r.res.ok&&r.data.version===pkg.version);

    r=await json(base,'/api/projects');
    check('anonymous project list hides Members project',r.res.ok&&!r.data.projects.some(p=>p.id==='p_knob'));
    r=await json(base,'/api/projects/p_knob');check('anonymous direct project route hides Members project',r.res.status===404);
    r=await json(base,'/api/home');check('anonymous Home feed hides Members project',r.res.ok&&!r.data.projects.some(p=>p.id==='p_knob')&&!r.data.continueProject);
    check('First Visit has at least three public project choices',r.res.ok&&r.data.projects.length>=3&&r.data.projects.every(p=>p.visibility==='Public'));
    r=await json(base,'/api/community-builds');check('First Visit has a public Community Build choice',r.res.ok&&r.data.items.some(x=>x.visibility==='Public'));
    r=await json(base,'/api/people');const publicPeople=Array.isArray(r.data.people)?r.data.people:[];
    const publicCrews=await json(base,'/api/crews');check('First Visit has a public maker or Crew connection',r.res.ok&&publicCrews.res.ok&&(publicPeople.length+publicCrews.data.items.length)>0);
    r=await json(base,'/api/search?q=Cast%20Aluminum&kind=projects');check('anonymous search hides Members project',r.res.ok&&!r.data.projects.some(p=>p.id==='p_knob'));
    r=await json(base,'/api/ways-in');check('Personal Ways In require sign-in',r.res.status===401);
    r=await json(base,'/api/make-together');check('Make Together is publicly explorable without exposing private work',r.res.ok&&Array.isArray(r.data.openProjects)&&Array.isArray(r.data.hours)&&Array.isArray(r.data.outcomes)&&r.data.privateWork===false&&r.data.countsPublic===false&&r.data.myWork.length===0&&!r.data.openProjects.some(p=>p.visibility!=='Public'||'followerCount' in p||'commentCount' in p));
    r=await json(base,'/api/commons');const seededCommons=r.data.items?.find(x=>x.id==='commons_demo_have');check('Commons is publicly explorable in chronological order',r.res.ok&&r.data.orderedBy==='most recently updated'&&seededCommons?.kind==='Have'&&r.data.countsPublic===false&&r.data.items.every(x=>!('responseCount' in x)&&!('followerCount' in x)));
    r=await json(base,`/api/commons/${seededCommons?.id||'commons_demo_have'}`);check('Public Commons detail keeps private responses out of anonymous views',r.res.ok&&Array.isArray(r.data.responses)&&r.data.responses.length===0&&r.data.canManage===false&&!('address' in (r.data.item||{})));
    r=await json(base,'/api/search?q=gearmotors&kind=commons');check('Unified search finds Commons exchanges',r.res.ok&&r.data.commons?.some(x=>x.id==='commons_demo_have'&&x.kind==='Have'));
    r=await json(base,'/api/search?q=impossible%20bearings&kind=notes');check('Unified Notes search returns published Shop Notes',r.res.ok&&r.data.shopNotes.some(n=>n.id==='n1'));
    r=await json(base,'/api/search?q=vent&kind=help');check('Help search includes troubleshooting questions',r.res.ok&&r.data.help.some(x=>x.id==='q1'));

    const loginMike=await json(base,'/api/auth/dev-login',{method:'POST',body:{userId:'u_mike'}});const mike=cookieFrom(loginMike.res);
    check('development Mike login works',loginMike.res.ok&&mike.includes('='));
    r=await json(base,'/api/projects/p_knob',{cookie:mike});check('signed-in member can view Members project',r.res.ok&&r.data.project?.id==='p_knob');

    r=await json(base,'/api/crews/crew_21502',{cookie:mike});check('Existing Maker Crew receives deterministic fallback handle',r.res.ok&&r.data.item?.handle==='mc21502');
    r=await json(base,'/api/identity/check?address=mc21502');check('Crew handle occupies the shared global namespace',r.res.ok&&r.data.available===false&&r.data.entityType==='crew');
    r=await json(base,'/api/me/callsign',{method:'PUT',cookie:mike,body:{address:'qa-maker'}});check('Member can claim a callsign',r.res.ok&&r.data.address==='qa-maker'&&r.data.user?.callsign==='qa-maker');
    r=await json(base,'/api/identity/qa-maker');check('Callsign resolves through the global registry',r.res.ok&&r.data.entityType==='user'&&r.data.entityId==='u_mike');
    r=await json(base,'/api/crews/crew_21502/handle',{method:'PUT',cookie:mike,body:{address:'qa-maker'}});check('Crew cannot claim a person callsign',r.res.status===409);
    r=await json(base,'/api/me/callsign',{method:'PUT',cookie:mike,body:{address:'qa-maker-2'}});check('Member can rename callsign',r.res.ok&&r.data.address==='qa-maker-2');
    r=await json(base,'/api/identity/check?address=qa-maker');check('Retired callsign enters 30-day cooldown before reuse',r.res.ok&&r.data.available===false&&r.data.status==='cooldown'&&Boolean(r.data.availableAt));

    const mapCrewCreate=await json(base,'/api/crews',{method:'POST',cookie:mike,body:{code:'QA901',name:'One Click Map QA Crew',anchorPostalCode:'21502',cityRegion:'Cumberland, MD',country:'US',status:'Paused',visibility:'Private'}});
    const mapCrewId=mapCrewCreate.data.id;check('QA Crew can start hidden with no coordinates',mapCrewCreate.res.status===201&&mapCrewId);
    r=await json(base,`/api/crews/${mapCrewId}/map-enable`,{method:'POST',cookie:mike,body:{}});check('One-click Crew map enable succeeds',r.res.ok&&r.data.mapVisible===true&&Number.isFinite(Number(r.data.map?.latitude))&&r.data.item?.status==='Active'&&r.data.item?.visibility==='Public');
    r=await json(base,'/api/workshop-map');check('One-click map-enabled Crew appears on public Workshop Map',r.res.ok&&r.data.crews.some(c=>c.id===mapCrewId));
    r=await json(base,`/api/crews/${mapCrewId}/map-location`,{method:'PUT',cookie:mike,body:{latitude:39.68050852174287,longitude:-78.76667986159089}});check('Crew map latitude and longitude can be edited',r.res.ok&&Math.abs(Number(r.data.map?.latitude)-39.68050852174287)<1e-12&&Math.abs(Number(r.data.map?.longitude)+78.76667986159089)<1e-12&&r.data.map?.source==='Manual Crew marker');
    r=await json(base,'/api/workshop-map');const editedMapCrew=r.data.crews.find(c=>c.id===mapCrewId);check('Edited Crew coordinates immediately drive the public marker',r.res.ok&&Math.abs(Number(editedMapCrew?.latitude)-39.68050852174287)<1e-12&&Math.abs(Number(editedMapCrew?.longitude)+78.76667986159089)<1e-12);
    r=await json(base,`/api/crews/${mapCrewId}/map-location`,{method:'PUT',cookie:mike,body:{resetToAnchor:true}});check('Crew marker can reset to starred ZIP centroid',r.res.ok&&r.data.map?.postalCode==='21502'&&Number.isFinite(Number(r.data.map?.latitude))&&Number.isFinite(Number(r.data.map?.longitude))&&String(r.data.map?.source||'').includes('21502'));

    r=await json(base,'/api/crews/crew_21502/members/u_rin',{method:'PUT',cookie:mike,body:{role:'Moderator',status:'Active'}});check('Crew role update returns the live updated member',r.res.ok&&r.data.member?.role==='Moderator'&&r.data.member?.user_id==='u_rin');
    r=await json(base,'/api/crews/crew_21502',{cookie:mike});check('Crew role change is immediately visible on the next Crew payload',r.res.ok&&r.data.item?.members.some(m=>m.user_id==='u_rin'&&m.role==='Moderator'));
    await json(base,'/api/crews/crew_21502/members/u_rin',{method:'PUT',cookie:mike,body:{role:'Member',status:'Active'}});

    const privateCreate=await json(base,'/api/projects',{method:'POST',cookie:mike,body:{title:'Integration Private Project',visibility:'Private',status:'Active'}});
    const privateId=privateCreate.data.project?.id;check('owner can create Private project',privateCreate.res.status===201&&privateId);
    const loginLee=await json(base,'/api/auth/dev-login',{method:'POST',body:{userId:'u_lee'}});const lee=cookieFrom(loginLee.res);const loginMorgan=await json(base,'/api/auth/dev-login',{method:'POST',body:{userId:'u_morgan'}});const morgan=cookieFrom(loginMorgan.res);
    const commonsCreate=await json(base,'/api/commons',{method:'POST',cookie:lee,body:{kind:'Need',title:'Integration Commons hinge request',body:'A small quiet hinge or a repairable hinge pattern would unblock the enclosure revision.',category:'hardware',exchangeType:'Conversation',scope:'Workshop',projectId:'p_lora',visibility:'Public',status:'Open'}});const commonsId=commonsCreate.data.item?.id;check('Project owner can publish a Commons Need',commonsCreate.res.status===201&&commonsId&&commonsCreate.data.item.kind==='Need'&&commonsCreate.data.item.projectId==='p_lora');
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('Project payload includes linked Commons exchanges',r.res.ok&&r.data.commons?.some(x=>x.id===commonsId&&x.kind==='Need'));
    r=await json(base,'/api/make-together');check('Make Together includes public Commons exchanges without counts',r.res.ok&&r.data.commons?.some(x=>x.id===commonsId)&&!JSON.stringify(r.data.commons).includes('responseCount'));
    const commonsDraft=await json(base,'/api/commons',{method:'POST',cookie:lee,body:{kind:'Have',title:'Integration private local draft',body:'A draft local exchange with approximate region only.',scope:'Local',cityRegion:'Pittsburgh, PA',visibility:'Members',status:'Draft'}});const commonsDraftId=commonsDraft.data.item?.id;check('Commons supports member-only drafts with approximate region',commonsDraft.res.status===201&&commonsDraft.data.item?.status==='Draft'&&commonsDraft.data.item?.cityRegion==='Pittsburgh, PA');
    r=await json(base,'/api/commons');check('Commons drafts stay out of the public gallery',r.res.ok&&!r.data.items.some(x=>x.id===commonsDraftId));
    r=await json(base,'/api/commons?mine=1',{cookie:lee});check('Commons author can retrieve private drafts and own posts',r.res.ok&&r.data.items.some(x=>x.id===commonsDraftId&&x.status==='Draft')&&r.data.items.some(x=>x.id===commonsId));
    r=await json(base,`/api/commons/${commonsId}`,{cookie:morgan});check('Another member can see the public Commons post but not its private thread',r.res.ok&&r.data.item?.canRespond===true&&r.data.canManage===false&&r.data.responses?.length===0,JSON.stringify({status:r.res.status,item:r.data.item,canManage:r.data.canManage,responses:r.data.responses}));
    const commonsResponse=await json(base,`/api/commons/${commonsId}/responses`,{method:'POST',cookie:morgan,body:{message:'I can bring a hinge sample and compare it with the enclosure geometry this week.'}});const commonsResponseId=commonsResponse.data.response?.id;check('Member can send a private Commons response',commonsResponse.res.status===201&&commonsResponseId&&commonsResponse.data.response.status==='Open');
    r=await json(base,`/api/commons/${commonsId}`,{cookie:morgan});check('Responder can see only their own Commons response',r.res.ok&&r.data.responses?.some(x=>x.id===commonsResponseId&&x.message.includes('hinge sample'))&&r.data.responses?.every(x=>x.userId==='u_morgan'));
    r=await json(base,`/api/commons/${commonsId}`,{cookie:lee});check('Commons owner can review private responses in place',r.res.ok&&r.data.canManage===true&&r.data.responses?.some(x=>x.id===commonsResponseId&&x.userId==='u_morgan'));
    r=await json(base,`/api/commons-responses/${commonsResponseId}`,{method:'PUT',cookie:lee,body:{status:'Accepted'}});check('Commons owner can accept a response and match the exchange',r.res.ok&&r.data.status==='Accepted'&&r.data.entryStatus==='Matched');
    r=await json(base,'/api/commons');check('Matched Commons exchanges leave the open public gallery',r.res.ok&&!r.data.items.some(x=>x.id===commonsId));
    r=await json(base,'/api/notifications',{cookie:lee});check('Commons response creates one restrained owner notification',r.res.ok&&r.data.items.some(n=>String(n.body).includes('responded to your Commons post')));
    r=await json(base,'/api/unfinished');check('Unfinished gallery is public and chronological',r.res.ok&&Array.isArray(r.data.items)&&r.data.items.some(x=>x.id==='unfinished_demo')&&r.data.orderedBy==='most recently updated'&&r.data.items.every(x=>!('followerCount' in x)&&x.status==='Published'));
    const unfinishedCreate=await json(base,'/api/unfinished',{method:'POST',cookie:lee,body:{projectId:'p_lora',exists:'A sensor node is reading correctly on the bench.',stuck:'The enclosure overheats outdoors.',nextStep:'Build one vented nose and repeat the afternoon test.',helpNeeded:'Looking for passive ventilation examples.',visibility:'Public',status:'Published'}});const unfinishedId=unfinishedCreate.data.item?.id;check('Project owner can publish an unfinished snapshot',unfinishedCreate.res.status===201&&unfinishedId&&unfinishedCreate.data.item.nextStep.includes('vented nose'));
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('Project payload includes its unfinished snapshots',r.res.ok&&r.data.unfinished?.some(x=>x.id===unfinishedId&&x.stuck.includes('overheats')));
    r=await json(base,'/api/make-together');check('Make Together includes public unfinished work without counts',r.res.ok&&r.data.unfinished?.some(x=>x.id===unfinishedId)&&!JSON.stringify(r.data.unfinished).includes('followerCount'));
    const unfinishedDraft=await json(base,'/api/unfinished',{method:'POST',cookie:lee,body:{projectId:'p_lora',exists:'Draft state',stuck:'Draft uncertainty',nextStep:'Draft next step',visibility:'Public',status:'Draft'}});const unfinishedDraftId=unfinishedDraft.data.item?.id;check('Unfinished snapshots can be kept as drafts',unfinishedDraft.res.status===201&&unfinishedDraft.data.item?.status==='Draft');
    r=await json(base,'/api/unfinished');check('Unfinished drafts stay out of the public gallery',r.res.ok&&!r.data.items.some(x=>x.id===unfinishedDraftId));
    r=await json(base,'/api/unfinished?mine=1',{cookie:lee});check('Author can retrieve unfinished drafts privately',r.res.ok&&r.data.items.some(x=>x.id===unfinishedDraftId&&x.status==='Draft'));
    const privateUnfinished=await json(base,'/api/unfinished',{method:'POST',cookie:lee,body:{projectId:'p_lora',exists:'Private working state',stuck:'Private uncertainty',nextStep:'Private next step',visibility:'Private',status:'Published'}});const privateUnfinishedId=privateUnfinished.data.item?.id;
    r=await json(base,'/api/unfinished',{cookie:mike});check('Private unfinished snapshots are hidden from other members',privateUnfinished.res.status===201&&privateUnfinishedId&&r.res.ok&&!r.data.items.some(x=>x.id===privateUnfinishedId));
    r=await json(base,`/api/unfinished/${unfinishedId}`,{method:'PUT',cookie:lee,body:{nextStep:'Compare two vent geometries under the same conditions.',status:'Published'}});check('Owner can revise the next tiny step',r.res.ok);
    r=await json(base,`/api/unfinished/${unfinishedId}`,{method:'DELETE',cookie:lee});check('Owner can remove an unfinished snapshot without removing the Project',r.res.ok);
    const leeCallsign=await json(base,'/api/me/callsign',{method:'PUT',cookie:lee,body:{address:'qa-lee'}});check('Second member can claim callsign for collaboration QA',leeCallsign.res.ok&&leeCallsign.data.address==='qa-lee');
    r=await json(base,`/api/projects/${privateId}`,{cookie:lee});check('Private project hidden from another member',r.res.status===404);
    r=await json(base,`/api/projects/${privateId}`,{cookie:mike});check('Private project visible to owner',r.res.ok&&r.data.project?.id===privateId);
    r=await json(base,'/api/bench/u_mike',{cookie:lee});check('Member Bench hides another maker’s Private project',r.res.ok&&!r.data.projects.some(p=>p.id===privateId));
    const collabInvite=await json(base,`/api/projects/${privateId}/collaboration-invites`,{method:'POST',cookie:mike,body:{callsign:'@qa-lee',role:'Reviewer',message:'Please review this build.'}});check('Project owner can invite collaborator by callsign',collabInvite.res.status===201&&collabInvite.data.id);
    r=await json(base,`/api/collaboration-invites/${collabInvite.data.id}`,{method:'PUT',cookie:lee,body:{status:'Accepted'}});check('Callsign collaboration invitation can be accepted',r.res.ok&&r.data.status==='Accepted');
    r=await json(base,`/api/projects/${privateId}`,{cookie:mike});check('Accepted collaborator is visibly credited with role and callsign',r.res.ok&&r.data.collaborators.some(c=>c.user_id==='u_lee'&&c.role==='Reviewer'&&c.callsign==='qa-lee'));
    r=await json(base,'/api/skill-exchange',{cookie:mike});check('Skill Exchange returns explicit reciprocal matches',r.res.ok&&Array.isArray(r.data.matches)&&r.data.matches.some(x=>Number(x.matchScore)>0));

    r=await json(base,'/api/projects/p_lora',{method:'PUT',cookie:lee,body:{openSignals:['feedback','tester','unknown-signal'],openRequest:'Please test the enclosure outdoors and report condensation.'}});check('Project owner can open a Bench with validated signals',r.res.ok&&r.data.project?.openSignals?.length===2&&r.data.project.openSignals.includes('feedback')&&r.data.project.openSignals.includes('tester')&&!r.data.project.openSignals.includes('unknown-signal'));
    r=await json(base,'/api/projects/p_lora',{method:'PUT',cookie:mike,body:{openSignals:['variation']}});check('Only the project owner can change Open Bench signals',r.res.status===403);
    r=await json(base,`/api/projects/${privateId}`,{method:'PUT',cookie:mike,body:{openSignals:['hand'],openRequest:'Private invitation QA'}});check('Private project can keep an owner-only Open Bench signal',r.res.ok&&r.data.project?.openSignals?.includes('hand'));
    r=await json(base,'/api/open-benches');check('Public Open Benches expose visible invitations in updated order',r.res.ok&&r.data.projects.some(p=>p.id==='p_lora'&&p.openRequest.includes('condensation')));
    check('Public Open Benches never leak private projects',r.res.ok&&!r.data.projects.some(p=>p.id===privateId));
    r=await json(base,'/api/ways-in',{cookie:mike});check('Ways In connect a member to visible Open Benches with plain-language reasons',r.res.ok&&r.data.orderedBy==='recent project updates'&&r.data.projects.some(p=>p.id==='p_lora'&&p.ownerId!=='u_mike'&&p.wayIn?.reasons?.length));
    r=await json(base,'/api/search?q=condensation&kind=open',{cookie:mike});check('Unified search finds Open Benches by invitation detail',r.res.ok&&r.data.openBenches.some(p=>p.id==='p_lora'&&p.wayIn?.reasons?.length));
    const openBenchResponse=await json(base,'/api/projects/p_lora/handshakes',{method:'POST',cookie:mike,body:{signal:'tester',message:'I can run a two-night outdoor condensation test.'}});const handshakeId=openBenchResponse.data.handshake?.id;check('Member can extend a structured Bench Handshake',openBenchResponse.res.status===201&&handshakeId&&openBenchResponse.data.handshake.status==='Offered');
    r=await json(base,'/api/projects/p_lora');check('Bench Handshake remains attached to the public project',r.res.ok&&r.data.handshakes.some(h=>h.id===handshakeId&&h.signal==='tester'));
    r=await json(base,'/api/projects/p_lora/handshakes',{method:'POST',cookie:mike,body:{signal:'tester',message:'Duplicate active offer'}});check('Duplicate active Bench Handshake is rejected',r.res.status===409);
    r=await json(base,'/api/projects/p_lora/handshakes',{method:'POST',cookie:mike,body:{signal:'materials',message:'Signal is not open'}});check('Bench Handshake requires an active invitation signal',r.res.status===400);
    r=await json(base,`/api/projects/p_lora/handshakes/${handshakeId}`,{method:'PUT',cookie:lee,body:{status:'Acknowledged',ownerNote:'Yes — please use the north-facing test location.'}});check('Project owner can acknowledge a Bench Handshake',r.res.ok&&r.data.handshake?.status==='Acknowledged'&&r.data.handshake?.owner_note.includes('north-facing'));
    r=await json(base,`/api/projects/p_lora/handshakes/${handshakeId}`,{method:'PUT',cookie:mike,body:{status:'Completed'}});check('Offering maker cannot close a Bench Handshake as completed',r.res.status===400);
    r=await json(base,`/api/projects/p_lora/handshakes/${handshakeId}`,{method:'PUT',cookie:lee,body:{status:'Completed',ownerNote:'Outdoor test completed and documented.'}});check('Project owner can mark offered help as landed',r.res.ok&&r.data.handshake?.status==='Completed');
    const withdrawOffer=await json(base,'/api/projects/p_lora/handshakes',{method:'POST',cookie:mike,body:{signal:'feedback',message:'I can review the enclosure drawing.'}});r=await json(base,`/api/projects/p_lora/handshakes/${withdrawOffer.data.handshake?.id}`,{method:'PUT',cookie:mike,body:{status:'Withdrawn'}});check('Offering maker can withdraw an active Bench Handshake',r.res.ok&&r.data.handshake?.status==='Withdrawn');
    r=await json(base,'/api/notifications',{cookie:lee});check('Bench Handshake creates one restrained owner notification',r.res.ok&&r.data.items.some(n=>String(n.body).includes('extended a Bench Handshake')));

    const hourStart=new Date(Date.now()+3*86400000),hourEnd=new Date(hourStart.getTime()+3600000);
    const hourBody={topic:'Outdoor enclosure test review',startsAt:hourStart.toISOString(),endsAt:hourEnd.toISOString(),timezone:'America/New_York',format:'Video / Voice',publicNote:'Bring condensation observations and one design question.',privateDetails:'Join https://example.test/private-bench-room',capacity:1};
    r=await json(base,'/api/projects/p_lora/bench-hours',{method:'POST',cookie:mike,body:hourBody});check('Only the Project owner can schedule an Open Bench Hour',r.res.status===403);
    const hourCreate=await json(base,'/api/projects/p_lora/bench-hours',{method:'POST',cookie:lee,body:hourBody});const hourId=hourCreate.data.hour?.id;check('Project owner can schedule bounded Open Bench Hours',hourCreate.res.status===201&&hourId&&hourCreate.data.hour.spaceStatus==='Available');
    r=await json(base,'/api/open-bench-hours');const publicHour=r.data.hours?.find(h=>h.id===hourId);check('Open Bench Hours are discoverable soonest first without private details',r.res.ok&&r.data.orderedBy==='soonest first'&&r.data.countsPublic===false&&publicHour&&!publicHour.privateDetails&&!publicHour.requests?.length);
    const hourRequest=await json(base,`/api/open-bench-hours/${hourId}/requests`,{method:'POST',cookie:mike,body:{note:'I can bring two nights of sensor data and a revised gasket sketch.'}});const hourRequestId=hourRequest.data.request?.id;check('Member can send a private Open Bench Hour request',hourRequest.res.status===201&&hourRequestId&&hourRequest.data.request.status==='Pending');
    r=await json(base,'/api/projects/p_lora',{cookie:mike});let memberHour=r.data.benchHours?.find(h=>h.id===hourId);check('Pending requester cannot see private connection details',r.res.ok&&memberHour?.myRequest?.status==='Pending'&&!memberHour.privateDetails);
    r=await json(base,'/api/projects/p_lora',{cookie:lee});let ownerHour=r.data.benchHours?.find(h=>h.id===hourId);check('Host can privately review Open Bench Hour requests',r.res.ok&&ownerHour?.requests?.some(x=>x.id===hourRequestId&&x.note.includes('sensor data')));
    r=await json(base,'/api/make-together',{cookie:lee});check('Make Together gives the host a private action queue',r.res.ok&&r.data.privateWork===true&&r.data.myWork.some(x=>x.id===hourRequestId&&x.status==='NEEDS REPLY'&&x.copy.includes('sensor data')));
    r=await json(base,'/api/make-together');check('Make Together never leaks the private host request queue',r.res.ok&&r.data.privateWork===false&&r.data.myWork.length===0&&!JSON.stringify(r.data).includes('two nights of sensor data'));
    r=await json(base,`/api/open-bench-hours/${hourId}/requests/${hourRequestId}`,{method:'PUT',cookie:lee,body:{status:'Accepted'}});check('Host can accept an Open Bench Hour request',r.res.ok&&r.data.request?.status==='Accepted');
    r=await json(base,'/api/projects/p_lora',{cookie:mike});memberHour=r.data.benchHours?.find(h=>h.id===hourId);check('Accepted maker receives private connection details',r.res.ok&&memberHour?.myRequest?.status==='Accepted'&&memberHour.privateDetails.includes('private-bench-room'));
    r=await json(base,'/api/make-together',{cookie:mike});check('Make Together carries accepted-only connection details into My Shared Work',r.res.ok&&r.data.myWork.some(x=>x.id===hourRequestId&&x.status==='CONFIRMED'&&x.privateDetails.includes('private-bench-room')));
    const loginRin=await json(base,'/api/auth/dev-login',{method:'POST',body:{userId:'u_rin'}});const rin=cookieFrom(loginRin.res);
    r=await json(base,`/api/open-bench-hours/${hourId}/requests`,{method:'POST',cookie:rin,body:{note:'I would also like to join.'}});check('Open Bench Hour capacity is enforced without publishing a count',r.res.status===409);
    r=await json(base,'/api/calendar',{cookie:mike});check('Accepted Open Bench Hours join the existing calendar',r.res.ok&&r.data.items.some(x=>x.id===hourId&&x.source==='bench-hour'));
    const hourIcs=await fetch(base+'/api/calendar.ics',{headers:{cookie:mike}});const hourIcsText=await hourIcs.text();check('Accepted Open Bench Hours export through the existing ICS',hourIcs.ok&&hourIcsText.includes('Open Bench Hour: Outdoor enclosure test review'));
    r=await json(base,'/api/notifications',{cookie:lee});check('Open Bench Hour requests create one action-worthy host notification',r.res.ok&&r.data.items.some(n=>String(n.body).includes('requested a place at your Open Bench Hour')));
    r=await json(base,'/api/notifications',{cookie:mike});check('Open Bench Hour decisions notify the requesting maker',r.res.ok&&r.data.items.some(n=>String(n.body).includes('Open Bench Hour request was accepted')));
    const privateHour=await json(base,`/api/projects/${privateId}/bench-hours`,{method:'POST',cookie:mike,body:{topic:'Private prototype review',startsAt:new Date(hourStart.getTime()+86400000).toISOString(),endsAt:new Date(hourEnd.getTime()+86400000).toISOString(),timezone:'Local time',format:'Project Talk',capacity:2}});r=await json(base,'/api/open-bench-hours');check('Private Project Bench Hours never leak through discovery',privateHour.res.status===201&&r.res.ok&&!r.data.hours.some(h=>h.id===privateHour.data.hour?.id));
    r=await json(base,`/api/open-bench-hours/${hourId}`,{method:'PUT',cookie:mike,body:{status:'Cancelled'}});check('Only the host can cancel an Open Bench Hour',r.res.status===403);
    r=await json(base,`/api/open-bench-hours/${hourId}`,{method:'PUT',cookie:lee,body:{status:'Cancelled'}});check('Host can cancel an Open Bench Hour',r.res.ok&&r.data.status==='Cancelled');
    r=await json(base,'/api/notifications',{cookie:mike});check('Cancellation notifies accepted makers',r.res.ok&&r.data.items.some(n=>String(n.body).includes('Open Bench Hour you joined was cancelled')));

    r=await json(base,'/api/projects/p_lora/follow',{method:'POST',cookie:mike,body:{}});check('Member can follow a visible Project',r.res.ok&&r.data.following===true&&r.data.followerCount>=1);
    r=await json(base,'/api/projects/p_lora',{cookie:mike});check('Project payload reports active follow state',r.res.ok&&r.data.project?.following===true&&r.data.project?.followerCount>=1);
    const followLog=await json(base,'/api/projects/p_lora/logs',{method:'POST',cookie:lee,body:{type:'Test',title:'Follower notification QA',body:'A meaningful test update for project followers.'}});check('Project owner can add followed-project update',followLog.res.status===201);
    r=await json(base,'/api/search?q=Follower%20notification%20QA&kind=notes',{cookie:mike});check('Unified Notes search returns visible Project logs',r.res.ok&&r.data.buildLogs.some(l=>l.id===followLog.data.entry?.id));
    r=await json(base,'/api/notifications',{cookie:mike});check('Project follower receives restrained update notification',r.res.ok&&r.data.items.some(n=>n.kind==='project'&&String(n.body).includes('LoRa Environmental Sensor')));
    const rootComment=await json(base,'/api/projects/p_lora/comments',{method:'POST',cookie:mike,body:{body:'Could we document the power budget tradeoff here?'}});const rootCommentId=rootComment.data.comment?.id;check('Project comment can be created',rootComment.res.status===201&&rootCommentId);
    const replyComment=await json(base,'/api/projects/p_lora/comments',{method:'POST',cookie:lee,body:{body:'Yes — I will add the measured numbers.',parentId:rootCommentId}});check('Project comment supports one-level reply',replyComment.res.status===201&&replyComment.data.comment?.parent_id===rootCommentId);
    r=await json(base,'/api/projects/p_lora',{cookie:mike});check('Project reply is returned in the comment thread',r.res.ok&&r.data.comments.some(c=>c.id===replyComment.data.comment?.id&&c.parent_id===rootCommentId));
    r=await json(base,`/api/projects/p_lora/comments/${rootCommentId}/useful`,{method:'PUT',cookie:mike,body:{mark:'Changed the Build'}});check('Only the Project owner can mark a useful response',r.res.status===403);
    r=await json(base,`/api/projects/p_lora/comments/${rootCommentId}/useful`,{method:'PUT',cookie:lee,body:{mark:'Changed the Build',note:'This prompted a measured power-budget note.'}});check('Project owner can record why a response was useful',r.res.ok&&r.data.usefulness==='Changed the Build'&&r.data.usefulnessNote.includes('power-budget'));
    r=await json(base,'/api/projects/p_lora',{cookie:mike});check('Useful Response stays attached to the Project conversation',r.res.ok&&r.data.comments.some(c=>c.id===rootCommentId&&c.usefulness==='Changed the Build'&&c.usefulness_note.includes('power-budget')));
    r=await json(base,'/api/notifications',{cookie:mike});check('Useful Response mark creates one action-worthy notification',r.res.ok&&r.data.items.some(n=>String(n.body).includes('marked “Changed the Build”')),JSON.stringify((r.data.items||[]).slice(0,5)));
    r=await json(base,`/api/projects/p_lora/comments/${rootCommentId}`,{method:'PUT',cookie:mike,body:{body:'Edited project comment for QA'}});check('Member can edit own project comment',r.res.ok);
    r=await json(base,'/api/projects/p_lora',{cookie:mike});check('Edited project comment is returned immediately',r.res.ok&&r.data.comments.some(c=>c.id===rootCommentId&&c.body==='Edited project comment for QA'));
    const deleteComment=await json(base,'/api/projects/p_lora/comments',{method:'POST',cookie:mike,body:{body:'Temporary removable comment'}});const deleteCommentId=deleteComment.data.comment?.id;
    r=await json(base,`/api/projects/p_lora/comments/${deleteCommentId}`,{method:'DELETE',cookie:mike});check('Member can delete own project comment',r.res.ok);
    r=await json(base,'/api/projects/p_lora',{cookie:mike});check('Deleted project comment disappears immediately',r.res.ok&&!r.data.comments.some(c=>c.id===deleteCommentId));
    const mentionComment=await json(base,'/api/projects/p_lora/comments',{method:'POST',cookie:lee,body:{body:'@qa-maker-2 could you look at the enclosure note?'}});check('Project comment accepts global callsign mention',mentionComment.res.status===201);
    r=await json(base,'/api/notifications',{cookie:mike});check('Global callsign mention creates notification',r.res.ok&&r.data.items.some(n=>n.kind==='mention'&&String(n.body).includes('@qa-maker-2')));

    const usefulQuestion=await json(base,'/api/questions',{method:'POST',cookie:mike,body:{title:'Useful answer notification QA',trying:'Verify the answer outcome loop.',helpNeeded:'A concrete next step.'}});const usefulQuestionId=usefulQuestion.data.id;check('Useful Response QA question can be created',usefulQuestion.res.status===201&&usefulQuestionId);
    const usefulAnswer=await json(base,`/api/questions/${usefulQuestionId}/answers`,{method:'POST',cookie:lee,body:{body:'Measure the idle draw before changing the sample interval.'}});const usefulAnswerId=usefulAnswer.data.id;check('Another maker can add a useful answer',usefulAnswer.res.status===201&&usefulAnswerId);
    r=await json(base,`/api/questions/${usefulQuestionId}/answers/${usefulAnswerId}/mark`,{method:'PUT',cookie:mike,body:{mark:'Helped'}});check('Question author can mark an answer as helpful',r.res.ok&&r.data.mark==='Helped'&&r.data.status==='Open');
    r=await json(base,'/api/notifications',{cookie:lee});check('Useful answer mark notifies its contributor',r.res.ok&&r.data.items.some(n=>String(n.body).includes('your answer was marked “Helped”')));

    r=await json(base,'/api/projects/p_lora',{cookie:mike});check('Build Fit is returned for visible projects',r.res.ok&&r.data.project?.fit&&typeof r.data.project.fit.score==='number');
    await json(base,'/api/projects/p_lora',{method:'PUT',cookie:lee,body:{openSignals:['feedback','tester','variation'],openRequest:'Please test the enclosure or make a variation.'}});
    const variationOffer=await json(base,'/api/projects/p_lora/handshakes',{method:'POST',cookie:mike,body:{signal:'variation',message:'I will make a low-power field version.'}});const variationHandshakeId=variationOffer.data.handshake?.id;check('Make a Variation can begin as a Bench Handshake',variationOffer.res.status===201&&variationHandshakeId);
    const clone=await json(base,'/api/projects/p_lora/clone',{method:'POST',cookie:mike,body:{title:'My LoRa Variation',adaptation:'Use the tools already on my Bench.',visibility:'Members',handshakeId:variationHandshakeId}});
    check('Make It Yours creates a linked personal variation',clone.res.status===201&&clone.data.project?.parentType==='Project'&&clone.data.project?.parentId==='p_lora'&&clone.data.project?.ownerId==='u_mike'&&clone.data.project?.variationIntent.includes('tools already'));
    if(clone.data.project?.id){
      r=await json(base,`/api/projects/${clone.data.project.id}`,{cookie:mike});check('Variation keeps source intent and starter Notebook entry',r.res.ok&&r.data.sourceProject?.id==='p_lora'&&r.data.project?.variationIntent.includes('tools already')&&r.data.logs?.some(x=>x.title==='Make It Yours'));
      r=await json(base,`/api/projects/${clone.data.project.id}`,{method:'PUT',cookie:mike,body:{status:'Complete',stage:'Complete',variationOutcome:'Cut idle draw by changing the sampling interval.'}});check('Completed variation records a concise returned outcome',r.res.ok&&r.data.project?.variationOutcome.includes('idle draw'));
      r=await json(base,'/api/projects/p_lora',{cookie:lee});check('Source Project collects visible Maker Variations with outcomes',r.res.ok&&r.data.variations.some(v=>v.id===clone.data.project.id&&v.status==='Complete'&&v.variationOutcome.includes('idle draw'))&&r.data.handshakes.some(h=>h.id===variationHandshakeId&&h.variation_project_id===clone.data.project.id));
      r=await json(base,'/api/make-together',{cookie:lee});check('Make Together closes the loop with documented shared-work outcomes',r.res.ok&&r.data.outcomes.some(x=>x.id===clone.data.project.id&&x.kind==='MAKER VARIATION'&&x.copy.includes('idle draw')));
    }
    const privateVariation=await json(base,'/api/projects/p_lora/clone',{method:'POST',cookie:mike,body:{title:'Private LoRa Variation',adaptation:'Keep this experiment private while it is unstable.',visibility:'Private'}});
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('Private Maker Variation is hidden from the source owner',privateVariation.res.status===201&&r.res.ok&&!r.data.variations.some(v=>v.id===privateVariation.data.project?.id));
    r=await json(base,'/api/projects/p_lora',{cookie:mike});check('Private Maker Variation remains visible to its own maker',r.res.ok&&r.data.variations.some(v=>v.id===privateVariation.data.project?.id));

    const teamCreate=await json(base,'/api/community-build-teams',{method:'POST',cookie:mike,body:{sourceType:'BUILD ALONG',sourceId:'ba1',title:'Integration Build Team',lookingFor:'electronics, documentation, testing'}});check('Member can form a Community Build team',teamCreate.res.status===201&&teamCreate.data.id);
    r=await json(base,`/api/community-build-teams/${teamCreate.data.id}/join`,{method:'POST',cookie:lee,body:{}});check('Another member can join a Community Build team',r.res.ok);
    r=await json(base,'/api/community-build-teams?sourceType=BUILD%20ALONG&sourceId=ba1',{cookie:mike});check('Community Build team exposes members and callsigns',r.res.ok&&r.data.teams.some(x=>x.id===teamCreate.data.id&&x.member_count===2&&x.members.some(m=>m.callsign==='qa-lee')));
    r=await json(base,'/api/community-builds',{cookie:mike});check('Community Build aggregate reports team count and membership',r.res.ok&&r.data.items.some(x=>x.type==='BUILD ALONG'&&x.id==='ba1'&&x.teamCount>=1&&x.myTeam===true));

    r=await json(base,'/api/profile',{method:'PUT',cookie:mike,body:{workingOn:'Testing a Phase 3 community build',workingOnDays:7}});check('Working On status can be set from My Bench',r.res.ok&&r.data.user?.workingOn==='Testing a Phase 3 community build'&&Boolean(r.data.user?.workingOnExpiresAt));
    r=await json(base,'/api/bench/u_mike',{cookie:lee});check('Active Working On status is visible on a member Bench',r.res.ok&&r.data.user?.workingOn==='Testing a Phase 3 community build');
    r=await json(base,'/api/home',{cookie:mike});check('Home returns Around the Workshop activity',r.res.ok&&Array.isArray(r.data.aroundWorkshop)&&r.data.aroundWorkshop.length>0);
    r=await json(base,'/api/community-builds',{cookie:mike});check('Community Builds return recent Maker Variations',r.res.ok&&Array.isArray(r.data.recentVariations));
    const liveList=await json(base,'/api/live',{cookie:mike});const liveForAttendance=liveList.data.items?.find(x=>x.event_type!=='After Hours');
    if(liveForAttendance){r=await json(base,`/api/live/${liveForAttendance.id}/attendance`,{method:'POST',cookie:mike,body:{status:'Going'}});check('Member can mark I’m Going on a Live event',r.res.ok&&r.data.status==='Going');r=await json(base,`/api/live/${liveForAttendance.id}`,{cookie:mike});check('Live event exposes visible attendance',r.res.ok&&r.data.myAttendance==='Going'&&r.data.attendance.some(a=>a.user_id==='u_mike'&&a.status==='Going'));}else check('Live event attendance fixture exists',false);

    for(const [name,url,key] of [
      ['Community Builds aggregate','/api/community-builds','items'],['Help aggregate','/api/help','items'],['Calendar aggregate','/api/calendar','items']]){
      r=await json(base,url,{cookie:mike});check(`${name} responds`,r.res.ok&&Array.isArray(r.data[key]));
    }
    const ics=await fetch(base+'/api/calendar.ics',{headers:{cookie:mike}});const icsText=await ics.text();check('Calendar ICS export responds',ics.ok&&icsText.includes('BEGIN:VCALENDAR'));
    r=await json(base,'/api/version-diagnostics',{cookie:mike});check('Version diagnostics aligns',r.res.ok&&r.data.serverVersion===pkg.version);
    r=await json(base,'/api/instruments',{cookie:mike});check('Retired Field Instrument Lab API is not routable',r.res.status===404);

    r=await json(base,'/api/blocks/u_lee',{method:'POST',cookie:mike,body:{kind:'Mute'}});check('Mute relation can be created',r.res.status===201&&r.data.kind==='Mute');
    r=await json(base,'/api/blocks',{cookie:mike});check('Mute relation can be read',r.res.ok&&r.data.items.some(x=>x.blocked_user_id==='u_lee'&&x.kind==='Mute'));
    r=await json(base,'/api/blocks/u_lee',{method:'DELETE',cookie:mike});check('Mute/block relation can be removed',r.res.ok);

    const idem='integration-idem-'+Date.now();
    const createBody={title:'Idempotent Offline Project',visibility:'Private'};
    const first=await json(base,'/api/projects',{method:'POST',cookie:mike,headers:{'x-idempotency-key':idem},body:createBody});
    const second=await json(base,'/api/projects',{method:'POST',cookie:mike,headers:{'x-idempotency-key':idem},body:createBody});
    check('Idempotent write returns same created object',first.res.status===201&&second.res.status===201&&first.data.project?.id===second.data.project?.id);
    check('Idempotent replay is explicitly marked',second.res.headers.get('x-idempotent-replay')==='1');
    const crossAccount=await json(base,'/api/projects',{method:'POST',cookie:lee,headers:{'x-idempotency-key':idem},body:{...createBody,title:'Lee Scoped Idempotency Project'}});
    check('Idempotency keys are scoped per account',crossAccount.res.status===201&&crossAccount.data.project?.id!==first.data.project?.id&&crossAccount.res.headers.get('x-idempotent-replay')!=='1');
    r=await json(base,'/api/projects',{cookie:mike});check('Idempotent replay does not duplicate project',r.data.projects.filter(p=>p.title==='Idempotent Offline Project').length===1);

    r=await json(base,'/api/scrap-bin',{method:'POST',cookie:mike,body:{title:'Integration scrap',scope:'Will Ship',visibility:'Members'}});check('Scoped Scrap Exchange write works',r.res.status===201&&r.data.id);
    r=await json(base,'/api/scrap-bin?scope=Will%20Ship',{cookie:mike});check('Scoped Scrap Exchange filter works',r.res.ok&&r.data.items.some(x=>x.title==='Integration scrap'));

    r=await json(base,'/api/gather');const seededGather=r.data.items?.find(x=>x.id==='gather_repair_clinic');check('Gather Kits are publicly explorable in chronological order without counts',r.res.ok&&r.data.orderedBy==='most recently updated'&&seededGather?.status==='Published'&&r.data.countsPublic===false&&r.data.items.length>=4&&r.data.items.every(x=>!('likeCount' in x)&&!('followerCount' in x)));
    r=await json(base,'/api/gather/gather_repair_clinic');check('Seeded Gather detail exposes a complete, reusable run of show',r.res.ok&&r.data.item?.roles?.length>=3&&r.data.item?.stations?.length>=3&&r.data.item?.supplies?.length>=3&&r.data.item?.welcomePrompt&&r.data.item?.closingReflection);
    r=await json(base,'/api/search?q=repair%20clinic&kind=gather');check('Unified search finds Gather Kits as a bounded kind',r.res.ok&&r.data.gather?.some(x=>x.id==='gather_repair_clinic'));
    r=await json(base,'/api/make-together');check('Make Together carries public Gather Kits without popularity totals',r.res.ok&&r.data.gatherKits?.some(x=>x.id==='gather_repair_clinic')&&r.data.countsPublic===false&&!JSON.stringify(r.data.gatherKits).includes('attendeeCount'));
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('Project payload carries its linked Gather Kit',r.res.ok&&r.data.gatherKits?.some(x=>x.id==='gather_first_solder'&&x.projectId==='p_lora'));
    r=await json(base,'/api/crews/crew_21502',{cookie:mike});check('Maker Crew payload carries Crew and meetup Gather Kits',r.res.ok&&r.data.item?.gatherKits?.some(x=>x.id==='gather_repair_clinic'&&x.crewEventId==='cevt_repair'));
    r=await json(base,'/api/sessions/sess_use',{cookie:lee});check('Session payload carries its host plan',r.res.ok&&r.data.item?.gatherKits?.some(x=>x.id==='gather_first_solder'&&x.sessionId==='sess_use'));
    r=await json(base,'/api/live/live2',{cookie:mike});check('Live detail carries its Gather Kit while event details remain canonical',r.res.ok&&r.data.gatherKits?.some(x=>x.id==='gather_neighborhood_scrap'&&x.liveEventId==='live2'));
    r=await json(base,'/api/calendar',{cookie:mike});check('Existing calendar items expose attached Gather Kits',r.res.ok&&r.data.items?.some(x=>x.gatherKits?.some(k=>k.id==='gather_repair_clinic')));
    r=await json(base,'/api/clinics/clinic1',{cookie:mike});check('Project Clinic reuses linked Gather Kits as its run of show',r.res.ok&&r.data.gatherKits?.some(x=>x.id==='gather_repair_clinic'));

    const gatherBody={title:'Integration Repair Gathering',eventType:'Repair Clinic',summary:'A repeatable shared repair session for testing the complete host workflow.',duration:'90 minutes',groupSize:'6–12 people',cityRegion:'Pittsburgh, PA',welcomePrompt:'What is one useful outcome for this object and its owner today?',roles:[{name:'Welcome lead',brief:'Orient people and notice access needs.'},{name:'Safety lead',brief:'Name hazards and stop conditions.'}],stations:[{name:'Triage',purpose:'Understand the symptom before opening the object.',supplies:'labels, markers'},{name:'Repair bench',purpose:'Make and test one bounded intervention.',supplies:'hand tools, task lights'}],supplies:['labels and markers','basic hand tools','task lights'],setupChecklist:['Clear the arrival path.','Post the stop conditions.'],accessibilityNotes:'Offer seated and standing work, task lighting, and more than one way to participate.',safetyNotes:'Stop mains-powered or safety-critical work when the room lacks the right equipment or competence.',closingReflection:'What changed, what remains uncertain, and what is the next safe step?',followUp:'Return each object with a short written handoff.',tags:['integration','repair','gather'],projectId:'p_lora',visibility:'Public',status:'Published'};
    const gatherCreate=await json(base,'/api/gather',{method:'POST',cookie:lee,body:gatherBody});const gatherId=gatherCreate.data.item?.id;check('Project owner can publish a structured Gather Kit',gatherCreate.res.status===201&&gatherId&&gatherCreate.data.item?.roles?.length===2&&gatherCreate.data.item?.stations?.length===2&&gatherCreate.data.item?.projectId==='p_lora',JSON.stringify(gatherCreate.data));
    const deniedGather=await json(base,'/api/gather',{method:'POST',cookie:morgan,body:{...gatherBody,title:'Unauthorized Project Gathering'}});check('A maker cannot attach a Gather Kit to another maker’s Project',deniedGather.res.status===403&&String(deniedGather.data.error||'').includes('Project team'));
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('A new Gather Kit is immediately attached to its Project',r.res.ok&&r.data.gatherKits?.some(x=>x.id===gatherId));
    r=await json(base,'/api/gather/'+gatherId);const publicGatherItem=r.data.item||{};check('Public Gather detail omits exact venue and private connection fields',r.res.ok&&publicGatherItem.id===gatherId&&publicGatherItem.cityRegion==='Pittsburgh, PA'&&!['address','exactAddress','privateDetails','venueName'].some(k=>k in publicGatherItem),JSON.stringify(publicGatherItem));
    r=await json(base,'/api/gather/'+gatherId+'/save',{method:'POST',cookie:morgan});check('Another maker can save a public Gather Kit privately',r.res.ok&&r.data.saved===true);
    r=await json(base,'/api/saved',{cookie:morgan});check('Saved shelf returns saved Gather Kits',r.res.ok&&r.data.gatherKits?.some(x=>x.id===gatherId));
    const gatherCopy=await json(base,'/api/gather/'+gatherId+'/duplicate',{method:'POST',cookie:morgan,body:{title:'Morgan’s Adapted Repair Gathering'}});const gatherCopyId=gatherCopy.data.item?.id;check('Use this kit creates an attributed private draft',gatherCopy.res.status===201&&gatherCopyId&&gatherCopy.data.item?.sourceKitId===gatherId&&gatherCopy.data.item?.visibility==='Private'&&gatherCopy.data.item?.status==='Draft');
    check('A copied kit drops context the new host cannot manage',gatherCopy.data.item?.projectId===''&&gatherCopy.data.item?.roles?.length===2&&gatherCopy.data.item?.stations?.length===2,JSON.stringify(gatherCopy.data.item));
    r=await json(base,'/api/gather/'+gatherCopyId,{cookie:lee});check('A private Gather draft is hidden from the source maker',r.res.status===404);
    r=await json(base,'/api/gather?mine=1',{cookie:morgan});check('Gather host can retrieve private drafts in My Kits',r.res.ok&&r.data.items?.some(x=>x.id===gatherCopyId&&x.status==='Draft'));
    r=await json(base,'/api/gather/'+gatherId);check('Duplicating a Gather Kit leaves the source published and unchanged',r.res.ok&&r.data.item?.status==='Published'&&r.data.item?.version===1&&r.data.item?.title==='Integration Repair Gathering');
    r=await json(base,'/api/gather/'+gatherCopyId,{method:'PUT',cookie:morgan,body:{title:'Morgan’s Neighborhood Repair Table',projectId:'p_stitch'}});check('Copy owner can adapt and attach their private draft to an owned Project',r.res.ok&&r.data.item?.version===2&&r.data.item?.projectId==='p_stitch'&&r.data.item?.status==='Draft');
    r=await json(base,'/api/projects/p_stitch',{cookie:morgan});check('Project owner sees an attached private Gather draft in context',r.res.ok&&r.data.gatherKits?.some(x=>x.id===gatherCopyId&&x.status==='Draft'));
    r=await json(base,'/api/export',{cookie:lee});check('Personal export includes owned and Project-linked Gather Kits',r.res.ok&&r.data.gatherKits?.some(x=>x.id===gatherId));
    r=await json(base,'/api/gather/'+gatherCopyId,{method:'DELETE',cookie:morgan});check('Copy owner can remove an adaptation without removing its source',r.res.ok&&r.data.ok===true);
    r=await json(base,'/api/gather/'+gatherId);check('Source Gather Kit remains after an adaptation is removed',r.res.ok&&r.data.item?.id===gatherId);
    const privateGather=await json(base,'/api/gather',{method:'POST',cookie:lee,body:{...gatherBody,title:'Private Integration Gather',projectId:'',visibility:'Private',status:'Published'}});const privateGatherId=privateGather.data.item?.id;
    r=await json(base,'/api/gather');check('Private published Gather Kits stay out of public discovery',privateGather.res.status===201&&privateGatherId&&r.res.ok&&!r.data.items.some(x=>x.id===privateGatherId));
    r=await json(base,'/api/gather/'+privateGatherId,{cookie:morgan});check('Private Gather detail is hidden from another member',r.res.status===404);
    r=await json(base,'/api/gather/'+privateGatherId,{cookie:lee});check('Private Gather detail remains available to its maker',r.res.ok&&r.data.item?.id===privateGatherId);
    await json(base,'/api/gather/'+privateGatherId,{method:'DELETE',cookie:lee});
    await json(base,'/api/gather/'+gatherId,{method:'DELETE',cookie:lee});

    r=await json(base,'/api/quests');const seededQuest=r.data.items?.find(x=>x.id==='quest_repair_small');check('Local Quests are publicly explorable in chronological order without counts',r.res.ok&&r.data.orderedBy==='most recently updated'&&r.data.countsPublic===false&&r.data.items.length>=6&&seededQuest?.questType==='Repair'&&r.data.items.every(x=>!('completionCount' in x)&&!('followerCount' in x)));
    r=await json(base,'/api/quests/quest_repair_small');check('Seeded Local Quest detail exposes a bounded prompt and support notes',r.res.ok&&r.data.item?.prompt&&r.data.item?.materials?.length>=2&&r.data.item?.accessNotes&&r.data.item?.safetyNotes&&r.data.item?.placeHint&&!r.data.item?.address);
    r=await json(base,'/api/search?q=repair&kind=quests');check('Unified search finds Local Quests as a bounded kind',r.res.ok&&r.data.quests?.some(x=>x.id==='quest_repair_small'));
    r=await json(base,'/api/home');check('Home carries public Local Quests without a new social feed',r.res.ok&&r.data.localQuests?.some(x=>x.id==='quest_repair_small')&&!JSON.stringify(r.data.localQuests).includes('completionCount'));
    r=await json(base,'/api/make-together');check('Make Together carries public Local Quests without completion totals',r.res.ok&&r.data.localQuests?.some(x=>x.id==='quest_repair_small')&&r.data.countsPublic===false&&!JSON.stringify(r.data.localQuests).includes('completionCount'));
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('Project payload carries its linked Local Quests',r.res.ok&&r.data.localQuests?.some(x=>x.id==='quest_field_card'&&x.projectId==='p_lora'));
    r=await json(base,'/api/crews/crew_21502',{cookie:mike});check('Maker Crew payload carries its linked Local Quests',r.res.ok&&r.data.item?.localQuests?.some(x=>x.id==='quest_ask_maker'&&x.crewId==='crew_21502'));

    const questBody={title:'Integration Local Repair Quest',questType:'Repair',summary:'A small place-aware repair prompt for testing the private field-note loop.',prompt:'Choose one non-critical object you are allowed to inspect. Name its expected behavior, record one clue, make one bounded change, and repeat the same test before deciding what to do next.',timebox:'25 minutes',placeHint:'A shared repair table or clear home work surface',materials:['the object and permission','a notebook or camera'],accessNotes:'Use a seated, verbal, photographed, or helper-supported version when handling tools is not the useful part.',safetyNotes:'Stop before mains-powered, pressurized, sharp, or safety-critical work without the right competence and equipment.',evidencePrompt:'Record the original symptom, one intervention, and the same test afterward.',reflectionPrompt:'What did the object teach you about where to stop?',tags:['integration','repair','local quest'],projectId:'p_lora',visibility:'Public',status:'Published'};
    const questCreate=await json(base,'/api/quests',{method:'POST',cookie:lee,body:questBody});const questId=questCreate.data.item?.id;check('Project owner can publish a Local Quest with bounded context',questCreate.res.status===201&&questId&&questCreate.data.item?.questType==='Repair'&&questCreate.data.item?.projectId==='p_lora'&&questCreate.data.item?.status==='Published',JSON.stringify(questCreate.data));
    const deniedQuest=await json(base,'/api/quests',{method:'POST',cookie:morgan,body:{...questBody,title:'Unauthorized Local Quest'}});check('A maker cannot attach a Local Quest to another maker’s Project',deniedQuest.res.status===403&&String(deniedQuest.data.error||'').includes('Project team'));
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('New Local Quest is immediately attached to its Project',r.res.ok&&r.data.localQuests?.some(x=>x.id===questId));
    r=await json(base,`/api/quests/${questId}`);check('Public Local Quest detail omits precise location fields',r.res.ok&&r.data.item?.placeHint==='A shared repair table or clear home work surface'&&!['address','coordinates','latitude','longitude'].some(k=>k in r.data.item));
    const memberQuest=await json(base,'/api/quests',{method:'POST',cookie:mike,body:{...questBody,title:'Members Only Local Quest',projectId:'p_knob',visibility:'Public'}});const memberQuestId=memberQuest.data.item?.id;check('Non-public Project context bounds a public quest to Members',memberQuest.res.status===201&&memberQuestId&&memberQuest.data.item?.visibility==='Members');
    r=await json(base,'/api/quests');check('Members-bound Local Quest stays out of anonymous discovery',r.res.ok&&!r.data.items.some(x=>x.id===memberQuestId));
    r=await json(base,`/api/quests/${memberQuestId}`,{cookie:morgan});check('Members-bound Local Quest is available to signed-in members',r.res.ok&&r.data.item?.visibility==='Members');
    r=await json(base,`/api/quests/${memberQuestId}`,{cookie:mike});check('Members-bound Local Quest remains visible to its maker',r.res.ok&&r.data.item?.visibility==='Members'&&r.data.item?.canEdit===true);

    const questStart=await json(base,`/api/quests/${questId}/start`,{method:'POST',cookie:morgan,body:{}});const attemptId=questStart.data.attempt?.id;check('Member can start a private Local Quest attempt',questStart.res.status===201&&attemptId&&questStart.data.attempt?.status==='Started'&&questStart.data.attempt?.visibility==='Private');
    r=await json(base,`/api/quests/${questId}`,{cookie:lee});check('In-progress Local Quest attempts stay out of another maker’s detail view',r.res.ok&&!r.data.attempts?.some(x=>x.id===attemptId)&&r.data.myAttempt===null);
    r=await json(base,`/api/quest-attempts/${attemptId}`,{method:'PUT',cookie:morgan,body:{status:'Started',notes:'I found a loose fastener and stopped before opening the powered enclosure.',visibility:'Public'}});check('In-progress attempt visibility is forced private',r.res.ok&&r.data.attempt?.status==='Started'&&r.data.attempt?.visibility==='Private');
    r=await json(base,`/api/quest-attempts/${attemptId}`,{method:'PUT',cookie:lee,body:{status:'Completed',notes:'I found a loose fastener and stopped before opening the powered enclosure.',visibility:'Public'}});check('Only the attempt maker can update a Local Quest field note',r.res.status===403);
    r=await json(base,`/api/quest-attempts/${attemptId}`,{method:'PUT',cookie:morgan,body:{status:'Completed',notes:'I found a loose fastener and stopped before opening the powered enclosure.',evidence:'The same symptom remained after tightening the external fastener.',reflection:'The useful result was knowing where the safe boundary was.',visibility:'Public'}});check('Completed Local Quest attempt can intentionally publish a field note',r.res.ok&&r.data.attempt?.status==='Completed'&&r.data.attempt?.visibility==='Public');
    r=await json(base,`/api/quests/${questId}`);check('Published field note appears on the Local Quest without a completion counter',r.res.ok&&r.data.attempts?.some(x=>x.id===attemptId&&x.visibility==='Public'&&x.notes.includes('loose fastener'))&&!JSON.stringify(r.data).includes('completionCount'));
    r=await json(base,`/api/quests/${questId}/save`,{method:'POST',cookie:morgan});check('Member can save a Local Quest privately',r.res.ok&&r.data.saved===true);
    r=await json(base,'/api/saved',{cookie:morgan});check('Saved shelf returns saved Local Quests',r.res.ok&&r.data.localQuests?.some(x=>x.id===questId));
    r=await json(base,'/api/export',{cookie:lee});check('Personal export includes owned Local Quests and their attempts',r.res.ok&&r.data.localQuests?.some(x=>x.id===questId)&&r.data.localQuestAttempts?.some(x=>x.quest_id===questId));
    r=await json(base,`/api/quests/${questId}`,{method:'DELETE',cookie:lee});check('Quest maker can remove a Local Quest without removing its Project',r.res.ok&&r.data.ok===true);
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('Removing a Local Quest leaves its Project intact',r.res.ok&&r.data.project?.id==='p_lora'&&!r.data.localQuests?.some(x=>x.id===questId));
    r=await json(base,`/api/quests/${memberQuestId}`,{method:'DELETE',cookie:mike});check('Quest maker can remove a Members-bound Local Quest',r.res.ok&&r.data.ok===true);

    r=await json(base,'/api/handoff');const seededHandoff=r.data.items?.find(x=>x.id==='handoff_demo_sensor');check('Handoff Field Cards are publicly explorable in updated order',r.res.ok&&r.data.orderedBy==='most recently updated'&&seededHandoff?.status==='Published'&&r.data.countsPublic===false);
    r=await json(base,'/api/home');check('Home carries the public Handoff Card lane',r.res.ok&&r.data.handoffCards?.some(x=>x.id==='handoff_demo_sensor'));
    r=await json(base,'/api/library');check('Library carries public Handoff Cards without replacing Shop Manual items',r.res.ok&&Array.isArray(r.data.items)&&r.data.handoffCards?.some(x=>x.id==='handoff_demo_sensor'));
    r=await json(base,'/api/search?q=low%20power&kind=handoff');check('Unified search finds Handoff Field Cards',r.res.ok&&r.data.handoff?.some(x=>x.id==='handoff_demo_sensor'));
    r=await json(base,'/api/make-together');check('Make Together carries public Handoff Cards without feedback totals',r.res.ok&&r.data.handoffCards?.some(x=>x.id==='handoff_demo_sensor')&&r.data.countsPublic===false&&!JSON.stringify(r.data.handoffCards).includes('feedback'));
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('Project payload carries linked Handoff Cards',r.res.ok&&r.data.handoffCards?.some(x=>x.id==='handoff_demo_sensor'&&x.projectId==='p_lora'));

    const handoffCreate=await json(base,'/api/handoff',{method:'POST',cookie:lee,body:{title:'Integration Handoff Card',summary:'A durable sequence for testing the learner loop.',practice:'Electronics',difficulty:'Approachable',estimatedTime:'20 minutes',tools:'multimeter, USB power meter',materials:'sensor board, jumper wires',stepsText:'Check the supply and ground.\n\nMeasure the idle current before changing the interval.',accessNotes:'Use the meter display or record the reading in a notebook.',safetyNotes:'Stop if the board or supply becomes unexpectedly hot.',commonMistakes:'Measuring while the sensor is actively transmitting.',troubleshooting:'Repeat the measurement with a known-good cable.',tags:'integration, sensor, handoff',projectId:'p_lora',visibility:'Public',status:'Published'}});const handoffId=handoffCreate.data.item?.id;check('Project owner can publish a Handoff Field Card',handoffCreate.res.status===201&&handoffId&&handoffCreate.data.item?.steps?.length===2&&handoffCreate.data.item?.projectId==='p_lora',JSON.stringify(handoffCreate.data));
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('New Handoff Card is immediately attached to its Project',r.res.ok&&r.data.handoffCards?.some(x=>x.id===handoffId));
    r=await json(base,'/api/handoff/'+handoffId);check('Anonymous Handoff detail exposes the usable sequence but no feedback',r.res.ok&&r.data.item?.id===handoffId&&r.data.item.steps.length===2&&Array.isArray(r.data.feedback)&&r.data.feedback.length===0,JSON.stringify(r.data));
    r=await json(base,'/api/handoff/'+handoffId+'/feedback',{method:'POST',body:{helped:'Anonymous feedback should be blocked.'}});check('Anonymous learners cannot submit Handoff feedback',r.res.status===401);
    const learnerFeedback=await json(base,'/api/handoff/'+handoffId+'/feedback',{method:'POST',cookie:mike,body:{helped:'The measurement sequence made the next test clear.',stuck:'I needed a reminder to wait for the sensor to settle.',adapted:'I used a USB power meter instead of the bench supply.',accessFeedback:'A larger check label would help on a small screen.'}});const learnerFeedbackId=learnerFeedback.data.feedback?.id;check('Signed-in learner can leave private Handoff feedback',learnerFeedback.res.status===201&&learnerFeedbackId&&learnerFeedback.data.feedback?.cardVersion===1);
    r=await json(base,'/api/handoff/'+handoffId,{cookie:lee});check('Card maker can see learner feedback privately',r.res.ok&&r.data.canManage===true&&r.data.feedback?.some(x=>x.id===learnerFeedbackId&&x.helped.includes('measurement sequence')));
    r=await json(base,'/api/handoff/'+handoffId,{cookie:morgan});check('A different learner cannot see another learner’s Handoff feedback',r.res.ok&&r.data.canManage===false&&r.data.feedback?.length===0&&r.data.myFeedback===null);
    r=await json(base,'/api/handoff?mine=1',{cookie:mike});check('My Handoff view includes cards I tried and my private notes',r.res.ok&&r.data.items?.some(x=>x.id===handoffId));
    r=await json(base,'/api/handoff/'+handoffId,{method:'PUT',cookie:lee,body:{summary:'Updated sequence for testing the learner loop.',stepsText:'Check the supply and ground.\n\nWait for the sensor to settle.\n\nMeasure the idle current.'}});check('Card maker can revise a Handoff Card and increment its version',r.res.ok&&r.data.item?.version===2&&r.data.item?.steps?.length===3,JSON.stringify(r.data));
    r=await json(base,'/api/handoff-feedback/'+learnerFeedbackId,{method:'PUT',cookie:lee,body:{status:'Addressed',ownerNote:'Added a settle-time check to the sequence.'}});check('Card maker can privately mark learner feedback addressed',r.res.ok&&r.data.status==='Addressed');
    r=await json(base,'/api/handoff/'+handoffId,{cookie:mike});check('Learner can see only their private feedback status and maker note',r.res.ok&&r.data.myFeedback?.status==='Addressed'&&r.data.myFeedback?.ownerNote.includes('settle-time'),JSON.stringify(r.data));
    r=await json(base,'/api/handoff-feedback/'+learnerFeedbackId,{method:'PUT',cookie:mike,body:{status:'Withdrawn'}});check('Learner can withdraw their private Handoff note',r.res.ok&&r.data.status==='Withdrawn');
    r=await json(base,'/api/handoff/'+handoffId+'/save',{method:'POST',cookie:mike});check('Learner can save a Handoff Card privately',r.res.ok&&r.data.saved===true);
    r=await json(base,'/api/saved',{cookie:mike});check('Saved shelf returns saved Handoff Cards',r.res.ok&&r.data.handoffCards?.some(x=>x.id===handoffId));

    const privateHandoff=await json(base,'/api/handoff',{method:'POST',cookie:lee,body:{title:'Private Integration Handoff',summary:'This card stays with its maker while it is being tested.',stepsText:'Keep the experiment on the private bench.',visibility:'Private',status:'Published'}});const privateHandoffId=privateHandoff.data.item?.id;
    r=await json(base,'/api/handoff');check('Private Handoff Cards stay out of public discovery',privateHandoff.res.status===201&&r.res.ok&&!r.data.items.some(x=>x.id===privateHandoffId));
    r=await json(base,'/api/handoff/'+privateHandoffId,{cookie:mike});check('Private Handoff detail is hidden from another member',r.res.status===404);
    r=await json(base,'/api/handoff/'+privateHandoffId,{cookie:lee});check('Private Handoff detail remains available to its maker',r.res.ok&&r.data.item?.id===privateHandoffId);
    r=await json(base,'/api/handoff/'+handoffId,{method:'DELETE',cookie:lee});check('Card maker can remove a Handoff Card without removing its Project',r.res.ok&&r.data.ok===true);
    r=await json(base,'/api/projects/p_lora',{cookie:lee});check('Removing a Handoff Card leaves its Project intact',r.res.ok&&r.data.project?.id==='p_lora'&&!r.data.handoffCards?.some(x=>x.id===handoffId));
    r=await json(base,'/api/handoff/'+privateHandoffId,{method:'DELETE',cookie:lee});check('Card maker can remove a private Handoff Card',r.res.ok&&r.data.ok===true);
    r=await json(base,'/api/admin/reset-demo',{method:'POST',cookie:mike,body:{}});check('Admin demo reset clears Local Quest additions and reseeds the release examples',r.res.ok&&r.data.ok===true);
    r=await json(base,'/api/quests');check('Demo reset restores seeded Local Quests',r.res.ok&&r.data.items?.some(x=>x.id==='quest_ask_maker')&&!r.data.items.some(x=>x.title==='Integration Local Repair Quest'));
  }catch(err){check('integration harness completed',false,err.stack||err.message);}
  finally{child.kill('SIGTERM');setTimeout(()=>{try{child.kill('SIGKILL')}catch{}},500);try{fs.rmSync(dataDir,{recursive:true,force:true})}catch{}}
  let failed=0;for(const [name,ok,detail] of checks){console.log(`${ok?'PASS':'FAIL'}  ${name}${!ok&&detail?` — ${detail}`:''}`);if(!ok)failed++;}
  if(failed){console.error(`\n${failed} integration QA check(s) failed.\n${logs.slice(-2000)}`);process.exit(1);}else console.log(`\n${checks.length}/${checks.length} integration QA checks passed.`);
})().catch(err=>{console.error(err);process.exit(1)});
